/** Fixed, parameter-free private aggregates; permission checks remain in the caller. */
export const scannerMaintenanceCountsSQL = `select (select count(*)::int from private.source_health where not healthy) outages,(select count(*)::int from private.source_health where credits_remaining is not null and credits_remaining<10) quota_low,(select count(*)::int from private.source_health where last_success<clock_timestamp()-interval '3 minutes') stale,(select count(*)::int from private.tip_publications p join private.events e on e.id=p.event_id where e.start_at<clock_timestamp()-interval '6 hours' and coalesce((select s.result::text from private.settlement_events s where s.tip_id=p.id order by s.created_at desc,s.id desc limit 1),'pending') not in ('won','lost','void')) settlement_backlog,
 (select count(*)::int from private.scanner_candidates c join private.events e on e.id=c.event_id where e.start_at>clock_timestamp() and e.start_at<=clock_timestamp()+interval '2 hours' and not exists(select 1 from private.scanner_reviews r where r.candidate_id=c.id and r.status in ('APPROVED','REJECTED','EXPIRED','INVALIDATED'))) awaiting_review_near_start,
 ((select count(*)::int from private.provider_poll_runs where sport='results' and status='failed' and started_at>clock_timestamp()-interval '1 day')+(select count(*)::int from private.audit_events where action='results_ingestion_failure' and created_at>clock_timestamp()-interval '1 day')) results_ingestion_failure,
 (select count(*)::int from private.source_health where case when diagnostics->>'mappingFailures' ~ '^[0-9]+$' then (diagnostics->>'mappingFailures')::numeric>=5 else false end) mapping_failure_spike`;
export const scannerDailyCountsSQL = `select
 null::int active_edges,null::int below_minimum_edges,
 (select count(*)::int from private.tip_publications p where (select s.result::text from private.settlement_events s where s.tip_id=p.id order by s.created_at desc,s.id desc limit 1)='disputed') manual_review_settlements,
 (select count(*)::int from private.scanner_candidates c left join lateral(select status from private.scanner_reviews where candidate_id=c.id order by created_at desc,id desc limit 1)s on true where c.expires_at>clock_timestamp() and coalesce(s.status,'CANDIDATE') in ('CANDIDATE','NEEDS_REVIEW')) needs_review,
 (select count(*)::int from private.scanner_candidates c where c.expires_at<=clock_timestamp() and not exists(select 1 from private.scanner_reviews where candidate_id=c.id and status in ('APPROVED','REJECTED','INVALIDATED'))) expired_candidates,
 (select count(*)::int from private.scanner_reviews r join private.scanner_candidates c on c.id=r.candidate_id where r.status='APPROVED' and c.purpose='research') approved_research,
 (select count(*)::int from private.scanner_reviews r join private.scanner_candidates c on c.id=r.candidate_id where r.status='APPROVED' and c.purpose='paper') approved_paper,
 (select count(*)::int from private.tip_publications where evidence='live_published') live_publications,
 (select count(*)::int from private.tip_publications p join private.events e on e.id=p.event_id where e.start_at>clock_timestamp() and p.evidence='live_published') upcoming_publications,
 (select count(*)::int from private.tip_publications p where coalesce((select s.result::text from private.settlement_events s where s.tip_id=p.id order by s.created_at desc,s.id desc limit 1),'pending') not in ('won','lost','void')) pending_settlements,
 (select count(*)::int from private.tip_publications p where (select s.result::text from private.settlement_events s where s.tip_id=p.id order by s.created_at desc,s.id desc limit 1) in ('won','lost','void')) settled_publications,
 (select count(*)::int from private.community_edges where pricing_model='market_reference_v1' and submitted_at>=date_trunc('day',clock_timestamp() at time zone 'UTC') at time zone 'UTC') new_community_edges,
 (select count(*)::int from private.social_reports where status in ('open','escalated')) moderation_reports,
 (select count(*)::int from private.events) events,(select count(*)::int from private.markets) markets`;
