export const communityAdminSections = [
  ["overview", "Community overview"],
  ["reports", "Reports & moderation"],
  ["integrity", "Member integrity"],
  ["verification", "Edge verification review"],
  ["promotions", "Promotion review"],
  ["rules", "Top Docked rules"],
  ["leaderboard-audit", "Leaderboard audit"],
  ["competitions", "Competitions"],
  ["prizes", "Prize review"],
  ["deals", "Deals & sponsors"],
  ["membership", "Membership & entitlements"],
  ["notifications", "Notifications"],
  ["analytics", "Social analytics"],
] as const;
